temp: &temp
  username: postgres
  password: postgres
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: UTF8
  pool: 10
  timeout: 5000

development:
  <<: *temp
  database: temp_dev

test:
  <<: *temp
  database: temp_test

production:
  <<: *temp
  database: temp
